### ISSUE TITLE
Re-write README

### ISSUE THREAD

**Issue by arthurlockman** [arthurlockman/plonky#4]
Re-write README to reflect actual installation and usage instructions. Possibly include how to set up Pycharm with the Docker image as well for development.

**Comment by PeterMitrano** [comment]
Progress made with b5abae6b554d879f4a214489ca039b4e8ff149a1

**Comment by arthurlockman** [comment]
Fixed in ce043a77970a761cd47b0fb3cd6ef1f8ae2618f7.
